### ISSUE TITLE
[Feature] Enable boolean return in authenticate method

### ISSUE THREAD

**Issue by eljonathas** [jquant/jai-sdk.ts#7]
## Feature description

The `authenticate` method must return an authentication state after passing a client token to him. This is to avoid new requests when we only need to validate the provided token by the user.

**Comment by felipegouveiae** [comment]
@eljonathas the system will throw an error if something goes wrong. By "something going wrong" I mean if the authentication key has an invalid format. In order to know if the authentication key is valid, the user would have to do a request and then would get the result or an error in case the api key is invalid.
